name: Linux <Manual>

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'OS to build for'
        required: true
        type: choice
        options:
        - gnu-linux
        - ms-windows
        - macOS

jobs:
  build-linux:
    if: ${{ github.event.inputs.os == 'gnu-linux' }}
    name: Build ${{ matrix.arch }} ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        build_type: [Release] #Debug,
        os: [ubuntu-24.04]
        include:
          - os: ubuntu-24.04
            package: QGroundControl
            host: linux
            arch: linux_gcc_64

        exclude:
          - os: ubuntu-24.04-arm
            build_type: Debug

    defaults:
      run:
        shell: bash

    env:
      QT_VERSION: 6.10.0

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Initial Setup
        uses: ./.github/actions/common

      - name: Install Dependencies
        run: |
          chmod a+x ./tools/setup/install-dependencies-debian.sh
          sudo ./tools/setup/install-dependencies-debian.sh

      - name: Setup Caching
        uses: ./.github/actions/cache
        with:
          host: ${{ matrix.host }}
          target: ${{ matrix.arch }}
          build-type: ${{ matrix.build_type }}
          cpm-modules: ${{ runner.temp }}/build/cpm_modules

      - name: Install Qt for Linux
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: ${{ matrix.host }}
          target: desktop
          arch: ${{ matrix.arch }}
          dir: ${{ runner.temp }}
          modules: qtcharts qtlocation qtpositioning qtspeech qt5compat qtmultimedia qtserialport qtimageformats qtshadertools qtconnectivity qtquick3d qtsensors qtscxml
          setup-python: false
          cache: true

      # - name: Build GStreamer
      #   uses: ./.github/actions/gstreamer

      - name: Configure
        working-directory: ${{ runner.temp }}/build
        run: ${{ env.QT_ROOT_DIR }}/bin/qt-cmake -S ${{ github.workspace }} -B . -G Ninja
              -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
              -DQGC_BUILD_TESTING=${{ matrix.build_type == 'Debug' && 'ON' || 'OFF' }}
              -DQGC_STABLE_BUILD=${{ github.ref_type == 'tag' || contains(github.ref, 'Stable') && 'ON' || 'OFF' }}

      - name: Build
        working-directory: ${{ runner.temp }}/build
        run: cmake --build . --target all --config ${{ matrix.build_type }} --parallel

      - name: Verify Executable
        if: matrix.build_type == 'Release'
        working-directory: ${{ runner.temp }}/build/${{ matrix.build_type }}
        run: xvfb-run -a ./${{ matrix.package }} --simple-boot-test

      - name: Create AppImage
        working-directory: ${{ runner.temp }}/build
        run: cmake --install . --config ${{ matrix.build_type }}

      - name: Verify AppImage
        if: matrix.build_type == 'Release'
        working-directory: ${{ runner.temp }}/build
        run: xvfb-run -a ./Linux-${{ matrix.package }}-*.AppImage --simple-boot-test

      - name: Run Unit Tests
        if: matrix.build_type == 'Debug'
        working-directory: ${{ runner.temp }}/build
        run: xvfb-run -a ./Linux-${{ matrix.package }}-*.AppImage --unittest

      - name: Upload Build File
        if: matrix.build_type == 'Release'
        uses: ./.github/actions/upload
        with:
          artifact_name: Linux-${{ matrix.package }}-*.AppImage
          package_name: Linux-${{ matrix.package }}
#          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws_distribution_id: ${{ secrets.AWS_DISTRIBUTION_ID }}
#          github_token: ${{ secrets.GITHUB_TOKEN }}

  build-ms:
    if: ${{ github.event.inputs.os == 'ms-windows' }}
    name: Build ${{ matrix.arch }} ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
            host: windows
            arch: win64_msvc2022_64
            build_type: Release
            package: QGroundControl-*-installer-AMD64

#          - os: windows-11-arm
#            host: windows_arm64
#            arch: win64_msvc2022_arm64
#            build_type: Release
#            package: QGroundControl-installer-ARM64
#
#          - os: windows-2022
#            host: windows
#            arch: win64_msvc2022_arm64_cross_compiled
#            build_type: Release
#            package: QGroundControl-installer-AMD64-ARM64

    defaults:
      run:
        shell: cmd

    env:
      QT_VERSION: 6.10.0

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Common setup
        uses: ./.github/actions/common

      # - name: Install dependencies
      #   shell: pwsh
      #   run: ./tools/setup/install-dependencies-windows.ps1 -Force

      - name: Install GStreamer
        if: matrix.arch == 'win64_msvc2022_64'
        uses: blinemedical/setup-gstreamer@v1
        with:
          version: 1.22.12

      - name: Setup cache
        uses: ./.github/actions/cache
        with:
          host: ${{ matrix.host }}
          target: ${{ matrix.arch }}
          build-type: ${{ matrix.build_type }}
          cpm-modules: ${{ runner.temp }}\build\cpm_modules

      - name: Install Qt ${{ env.QT_VERSION }}
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: ${{ matrix.host }}
          target: desktop
          arch: ${{ matrix.arch }}
          dir: ${{ runner.temp }}
          modules: qtcharts qtlocation qtpositioning qtspeech qt5compat qtmultimedia qtserialport qtimageformats qtshadertools qtconnectivity qtquick3d qtsensors qtscxml
          setup-python: false
          cache: true

      - name: Set up MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ (matrix.arch == 'win64_msvc2022_64' && 'x64') || (matrix.arch == 'win64_msvc2022_arm64' && 'arm64') || 'amd64_arm64' }}

      - name: Configure
        working-directory: ${{ runner.temp }}\build
        run: |
          ${{ env.QT_ROOT_DIR }}\bin\qt-cmake -S ${{ github.workspace }} -B . -G Ninja ^
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ^
            -DQGC_STABLE_BUILD=${{ (github.ref_type == 'tag' || contains(github.ref, 'Stable')) && 'ON' || 'OFF' }} ^
            -DQGC_ENABLE_GST_VIDEOSTREAMING=${{ matrix.arch == 'win64_msvc2022_64' && 'ON' || 'OFF' }} ^
            -DQT_HOST_PATH=${{ (matrix.arch == 'win64_msvc2022_arm64_cross_compiled') && format('{0}\\..\\msvc2022_64', env.QT_ROOT_DIR) || '' }}

      - name: Build
        working-directory: ${{ runner.temp }}\build
        run: cmake --build . --target all --config ${{ matrix.build_type }} --parallel

      - name: Verify Executable
        if: matrix.build_type == 'Release' && matrix.arch != 'win64_msvc2022_arm64_cross_compiled'
        working-directory: ${{ runner.temp }}\build\${{ matrix.build_type }}
        run: QGroundControl.exe --simple-boot-test

      - name: Create Installer
        working-directory: ${{ runner.temp }}\build
        run: cmake --install . --config ${{ matrix.build_type }}

      - name: Find Installer
        shell: pwsh
        run: |
          $installer = Get-ChildItem -Path "${{ runner.temp }}\build" -Recurse -Filter "Windows-QGroundControl-*.exe" | Select-Object -First 1
          if ($null -eq $installer) {
            Write-Error "Installer not found!"
            exit 1
          }
          echo "INSTALLER_FILE=$($installer.Name)" >> $env:GITHUB_ENV
          echo "INSTALLER_NAME=$($installer.BaseName)" >> $env:GITHUB_ENV
          echo "Found installer: $($installer.Name)"

      - name: Upload artifact (installer)
        if: matrix.build_type == 'Release'
        uses: ./.github/actions/upload
        with:
          artifact_name: ${{ env.INSTALLER_FILE }}
          package_name: ${{ env.INSTALLER_NAME }}
  
  build-macOS:
    if: ${{ github.event.inputs.os == 'gnu-linux' }}
    runs-on: macos-latest

    strategy:
      matrix:
        BuildType: [Release]

    defaults:
      run:
        shell: bash

    env:
      QT_VERSION: 6.10.0

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Initial Setup
        uses: ./.github/actions/common

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '<=16.x'

      - name: Install Dependencies (include GStreamer)
        working-directory: ${{ github.workspace }}/tools/setup
        run: sh install-dependencies-osx.sh

      - name: Setup Caching
        uses: ./.github/actions/cache
        with:
          host: mac
          target: clang_64
          build-type: ${{ matrix.BuildType }}
          cpm-modules: ${{ runner.temp }}/build/cpm_modules

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: mac
          target: desktop
          arch: clang_64
          dir: ${{ runner.temp }}
          modules: qtcharts qtlocation qtpositioning qtspeech qt5compat qtmultimedia qtserialport qtimageformats qtshadertools qtconnectivity qtquick3d qtsensors qtscxml
          setup-python: false
          cache: true

      - name: CMake configure
        working-directory: ${{ runner.temp }}/build
        run: ${{ env.QT_ROOT_DIR }}/bin/qt-cmake -S ${{ github.workspace }} -B . -G Ninja
              -DCMAKE_BUILD_TYPE=${{ matrix.BuildType }}
              -DQGC_STABLE_BUILD=${{ github.ref_type == 'tag' || contains(github.ref, 'Stable') && 'ON' || 'OFF' }}
              -DQGC_MACOS_SIGN_WITH_IDENTITY='OFF'

      - name: Build
        working-directory: ${{ runner.temp }}/build
        run: cmake --build . --target all --config ${{ matrix.BuildType }} --parallel

      - name: Sanity check dev build executable
        working-directory: ${{ runner.temp }}/build/Release/QGroundControl.app/Contents/MacOS
        run: ./QGroundControl --simple-boot-test

      - name: Create DMG
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: ${{ runner.temp }}/build
        run: cmake --install . --config ${{ matrix.BuildType }}

      - name: Find DMG file
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        working-directory: ${{ runner.temp }}/build
        run: |
          DMG=$(find . -maxdepth 1 -name "MacOS-QGroundControl-*.dmg" -type f | head -n 1)
          if [ -z "$DMG" ]; then
            echo "DMG not found!"
            exit 1
          fi
          DMG_NAME=$(basename "$DMG")
          DMG_NAME_NO_EXT=$(basename "$DMG" .dmg)
          echo "DMG_FILE=$DMG_NAME" >> $GITHUB_ENV
          echo "DMG_NAME=$DMG_NAME_NO_EXT" >> $GITHUB_ENV
          echo "Found DMG: $DMG_NAME"

      - name: Mount DMG
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: ${{ runner.temp }}/build
        run: hdiutil attach "${{ env.DMG_FILE }}"

      - name: Sanity check DMG executable
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: /Volumes/QGroundControl/QGroundControl.app/Contents/MacOS
        run: ./QGroundControl --simple-boot-test

      - name: Unmount DMG
        if: startsWith(github.ref, 'refs/tags/')
        run: hdiutil detach /Volumes/QGroundControl || true

      - name: Upload Build File
        if: matrix.BuildType == 'Release' && startsWith(github.ref, 'refs/tags/')
        uses: ./.github/actions/upload
        with:
          artifact_name: ${{ env.DMG_FILE }}
          package_name: ${{ env.DMG_NAME }}

